### ISSUE TITLE
Mailbox API 2.0

### ISSUE THREAD

**Issue by dsshap** [Springest/help_scout#17]
Any plans to support Mailbox API 2.0?

> On June 6th, 2019, Mailbox API 1.0 will be sunsetted, and at that time any apps using this legacy API will no longer work.

**Comment by djfpaagman** [comment]
hi @dsshap, we're planning on working on that in the coming weeks. Do you have any particular use cases you want us to keep covered?

**Comment by gurs1kh** [comment]
any updates on this?

**Comment by gurs1kh** [comment]
I took it upon myself to get this work started.
Please see #18

**Comment by bittersweet** [comment]
I've merged the changes from #18  into a fresh branch , thanks again @gurs1kh ! I will continue to work on this branch before releasing a new version of the gem.

I will try to keep everyone updated in here on the progress, but as a small disclaimer, my focus will be on developing :-)

**Comment by jlawren311** [comment]
Are there any updates on the v2 upgrade? I see release `v1.0.0.beta1` was created back in August

**Comment by bittersweet** [comment]
Hi @jlawren311 , we've been using `v1.0.0.beta1` since then in production in various projects without any issues. 

About https://github.com/TrueLinkFinancial/help_scout/pull/1 : We have a `create_note` in the V2 API in the beta version:

https://github.com/Springest/help_scout/blob/833975d9163dc45224c7f011361dd838fae6c074/lib/help_scout.rb#L198-L207

Just like the V1 API gem version, we don't really support everything, just what we've needed so far ourselves. 

I'll push up a new version to indicate we are not really in beta anymore. Do you have any question about the V2 version?

**Comment by jlawren311** [comment]
Thanks for the quick response @bittersweet! We've been relying on v2 since May 2019 with a fork of this repo. I saw the `v1.0.0.beta1` release but noticed (1) it was still in beta and (2) there hadn't been any activity since August 2019.

**Comment by bittersweet** [comment]
I'm going to close this task as we now officially are on the v2 API version of HelpScout in master and rubygems. I apologize for not being very active with reporting on this. 

Updates:

* I have merged `api_v2` into master
* Master is now tagged as [2.0.0](https://github.com/Springest/help_scout/tree/v2.0.0)
* 2.0.0 is also up [at rubygems](https://rubygems.org/gems/help_scout/versions/2.0.0)

For us most of the work was related to figuring out what kind of objects HelpScout wanted in their V2 API. A lot of things you could do in one operation were now split up in to multiple steps, and we had to work around that as well.  

Are you on the V2 API with your fork? I've looked over the [differences between our code](https://github.com/TrueLinkFinancial/help_scout/compare/master...Springest:master), but I don't see anything blocking you from using this gem again. But also, I don't see how you could use the HS V2 API with that fork, because a lot of stuff was not in there yet, like the JSONPatch to update conversations etc.

**Comment by jlawren311** [comment]
I just tested against 2.0.0 and looks like the conversation and note were created as expected! 🎉 
@gurs1kh submitted a PR for the v2 upgrade last May and created a fork with that change while you all worked on upgrading this repo. Thankfully, that made it very simple to switch back to your gem with v2.0.0
